### ISSUE TITLE
Auto-resize doesn't trigger on dynamic menus

### ISSUE THREAD

**Issue by sefn** [sebgroup/ng-magic-iframe#20]
# How to reproduce

1) In IBF, go to a page that has a small vertical size, e.g. "Betala & överföra > Filregistrering SEK"

2) Open the sub-menu by clicking e.g. "Betala & överföra" in the menu bar

# Expected result

Magic iframe should auto-resize when the menu opens and goes below the vertical cut-off point.

# Actual result

The menu is cut off at the bottom because it reaches outside the iframe height. See screenshot below:

![image](https://user-images.githubusercontent.com/31542772/51102295-b1856a00-17de-11e9-928f-8abdc954ecf7.png)

This is the true size of the menu (an ul element):

![image](https://user-images.githubusercontent.com/31542772/51102410-25277700-17df-11e9-9088-069e80536f55.png)

**Comment by sefn** [comment]
@hjalmers I don't have permission to add the bug label

**Comment by sefn** [comment]
Another example:

![menu-cutoff](https://user-images.githubusercontent.com/31542772/51102496-8a7b6800-17df-11e9-847b-eb7ec0bb4d6d.png)

**Comment by hjalmers** [comment]
@sefn this is most likely due to the css that the iframed page uses so it's probably not really an issue with iframe but I'll look into it just to be sure before closing this issue. The iframe will resize as long as the height of the body element changes and I'm guessing this menu is added in away that it doesn't.
